"""Primera migración

Revision ID: 380f2b54d63b
Revises: 
Create Date: 2025-06-06 17:22:26.286545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380f2b54d63b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripcion')
    # ### end Alembic commands ###
